### ISSUE TITLE
BUG: unable to set extensions

### ISSUE THREAD

**Issue by snitin315** [tbjgolden/react-codemirror6#4]
Whenever I pass value to extensions prop, I see this error. I can reproduce this on the official website as well - 

https://tbjgolden.github.io/react-codemirror6/?path=/story/components-codemirror--primary

<img width="1121" alt="Screenshot 2022-03-23 at 7 03 47 AM" src="https://user-images.githubusercontent.com/46647141/159604406-629e23a2-2543-433a-9bf5-e72465a10f6a.png">

To reproduce just add language to extensions

**Comment by andrebnassis** [comment]
> Whenever I pass value to extensions prop, I see this error. I can reproduce this on the official website as well -
> 
> https://tbjgolden.github.io/react-codemirror6/?path=/story/components-codemirror--primary
> 
> <img alt="Screenshot 2022-03-23 at 7 03 47 AM" width="1121" src="https://user-images.githubusercontent.com/46647141/159604406-629e23a2-2543-433a-9bf5-e72465a10f6a.png">
> 
> To reproduce just add language to extensions

I just opened a pull request (#5) that fix this issue (found the solution here: https://github.com/codemirror/codemirror.next/issues/608).
@tbjgolden I don't know the rules to deploy a new package version, but I've opened a pull request. Let me know if it is missing something.

**Comment by tmgldn** [comment]
@andrebnassis thanks for writing that up and submitting a PR! I've merged it in and it has been released 😄

**Comment by andrebnassis** [comment]
> @andrebnassis thanks for writing that up and submitting a PR! I've merged it in and it has been released 😄

I just tested and the package is working good, but the storybook's demo page is broken. I think you just need to generate a new storybook-build and deploy it (do not need to generate a new release on the package itself).

**Comment by tmgldn** [comment]
Good to know, will fix when I get a chance!
