### ISSUE TITLE
get hold of editor view instance

### ISSUE THREAD

**Issue by felixroos** [tbjgolden/react-codemirror6#6]
Hello, and thanks for this super easy to use component, it really helps to get into codemirror 6 quickly!
I think it would be really helpful if the component could expose the editor view instance to the outside, so it can be used!
This could be done by adding a callback like `onInit` that is called with `view` after it's created here:

https://github.com/tbjgolden/react-codemirror6/blob/main/src/CodeMirrorLite/index.tsx#L91

I can also send a PR if you like.

**Comment by tmgldn** [comment]
Hey Felix! I've added an `onViewChange` prop that hopefully solves your problem!

https://github.com/tbjgolden/react-codemirror6/releases/tag/v1.1.0

**Comment by felixroos** [comment]
Thank you so much, it works fine!
