### ISSUE TITLE
Extension example

### ISSUE THREAD

**Issue by Tcheetox** [tbjgolden/react-codemirror6#7]
Hello,

Could you share an example using an extension (e.g. JSON language)? 
I tried to take a look at https://tbjgolden.github.io/react-codemirror6/ but couldn't see the code.

Thanks

**Comment by tmgldn** [comment]
Hi @Tcheetox 

Here's that same example buried in the storybook source code:

https://github.com/tbjgolden/react-codemirror6/blob/main/src/CodeMirror/index.stories.tsx#L139-L171

In this case, oneDark is the extension, but you could import other extensions like JSON language and use them in the same way.
