### ISSUE TITLE
Fixing the reactive part

### ISSUE THREAD

**Issue by elbakerino** [tbjgolden/react-codemirror6#8]
Hey,

are there plans/wishes to add the missing implementation of e.g. rebuilding an editor when e.g. extensions change?

tbh that's the whole part "why to use react": being able to change stuff by changing props - and libs imho must follow this, otherwise it's not really "a React Component".

> Note: I'm checking if there is a React CodeMirror v6 lib which I could use in the [code editor widget of ui-schema](https://github.com/ui-schema/ui-schema), which needs to change props completely dynamic to work

**Comment by tmgldn** [comment]
Hi there! I'm a bit too busy to make that side of things work.

You might prefer [@uiw/react-codemirror](https://github.com/uiwjs/react-codemirror) instead; it's under active dev and I think they managed to get things working reactively with extensions!
