### ISSUE TITLE
undo does not fire onChange

### ISSUE THREAD

**Issue by felixroos** [tbjgolden/react-codemirror6#9]
Hello! I noticed that the onChange callback is not fired when undoing a change.
you can test the behavior here: https://codesandbox.io/s/react-codemirror6-onchange-undo-bug-bo7wo6?file=/src/App.js
Is this a problem of this wrapper or maybe a codemirror issue?

**Comment by tmgldn** [comment]
Saw you managed to get it worked out with a new codemirror wrapper; nice!

I've updated this project to inform people to use that wrapper instead; I'm a little too busy to work on this right now but might pick up on it if that wrapper ends up with its own issues that I'd be able to fix!
